name: Benchmarking

on:
  pull_request:
    branches: [ main ]

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download benchmark data
        uses: actions/download-artifact@v4
        with:
          name: bench
          path: target/criterion
      - name: Run benchmarck
        run: cargo bench
      - name: Upload benchmark data
        uses: actions/upload-artifact@v4
        with:
          name: bench
          path: target/criterion
          overwrite: true