name: Benchmarking

on:
  pull_request:
    branches: [ main ]

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Run benchmarck (baseline)
        run: cargo bench
      - run: ls target
      - uses: actions/checkout@v4
        with:
          clean: false
      - run: ls target
      - name: Run benchmarck (changes)
        run: cargo bench
